# Generated by Django 3.0.1 on 2020-01-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('SKU', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('featureImg', models.ImageField(default='img.jpg', upload_to='images/')),
                ('displayImg', models.ImageField(default='img.jpg', upload_to='images/')),
                ('displayImgFirst', models.ImageField(default='img.jpg', upload_to='images/')),
                ('displayImgSecond', models.ImageField(default='img.jpg', upload_to='images/')),
                ('displayImgThird', models.ImageField(default='img.jpg', upload_to='images/')),
                ('xs', models.PositiveIntegerField(default=0)),
                ('sm', models.PositiveIntegerField(default=0)),
                ('md', models.PositiveIntegerField(default=0)),
                ('lg', models.PositiveIntegerField(default=0)),
                ('xl', models.PositiveIntegerField(default=0)),
                ('xxl', models.PositiveIntegerField(default=0)),
                ('xxxl', models.PositiveIntegerField(default=0)),
                ('type', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='product.Type')),
                ('vendor', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='product.Vendor')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
