# Generated by Django 3.0.1 on 2020-02-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200123_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='images/'),
        ),
    ]
