# Generated by Django 3.0.1 on 2020-02-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
