# Generated by Django 3.0.1 on 2020-02-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200210_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='displayImg',
        ),
    ]
