# Generated by Django 3.0.1 on 2020-02-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_customer_displayimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prodreview',
        ),
    ]
