# Generated by Django 3.0.1 on 2020-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_customer_prodreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='prodreview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
