# Generated by Django 3.0.1 on 2020-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_customize_reviewbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customize',
            old_name='reviewbanner',
            new_name='menbanner',
        ),
        migrations.AddField(
            model_name='customize',
            name='womenbanner',
            field=models.ImageField(default='hero.jpg', upload_to='images/'),
        ),
    ]
