# Generated by Django 3.0.1 on 2020-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200212_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='reviewsectiontitle',
            field=models.CharField(default='Our customers get all Apparel from us.', max_length=50),
        ),
    ]
