# Generated by Django 3.0.1 on 2020-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_customize_reviewsectiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='ghostbtntitle',
            field=models.CharField(default='Reviews', max_length=50),
        ),
        migrations.AddField(
            model_name='customize',
            name='herobtntitle',
            field=models.CharField(default='All Products', max_length=50),
        ),
    ]
