# Generated by Django 3.0.1 on 2020-02-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200212_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customize',
            name='mainbanner',
            field=models.ImageField(default='70550984_10157373051965535_3336865258831609856_n.jpg', upload_to='images/'),
        ),
    ]
